#ifndef LUOXI_LIB_GLOBAL_CONST_H
#define LUOXI_LIB_GLOBAL_CONST_H

#define LUOXI_CFG_GROUP_GLOBAL "Global"
#define LUOXI_CFG_GROUP_ZHUCHAO "ZhuChao"

#define UMM_LISTEN_PORT 7760
#define UMS_LISTEN_PORT 7770
#define MS_LISTEN_PORT 7780
#define LUOXI_LISTEN_PORT 7790

#endif // LUOXI_LIB_GLOBAL_CONST_H